# Generated by Django 3.1.2 on 2020-10-28 12:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactpage_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='landing_message',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_info',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
    ]
