# Generated by Django 3.1.2 on 2020-12-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_standardpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
