# Generated by Django 3.1.2 on 2020-10-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='service',
        ),
        migrations.AddField(
            model_name='professional',
            name='booking_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='services',
            field=models.ManyToManyField(blank=True, to='locations.Service'),
        ),
    ]
