# Generated by Django 3.1.2 on 2020-10-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20201026_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
