# Generated by Django 3.1.7 on 2021-05-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20210513_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['studio']},
        ),
    ]
