# Generated by Django 3.1.7 on 2022-07-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20210513_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
