# Generated by Django 3.1.7 on 2022-08-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_professional_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='shopping_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
